project:
  type: website
  render:
    - index.qmd
    - schedule.qmd
    - info.qmd
    - syllabus.qmd

website:
  title: "Population Genomics In Practice H24"
  navbar:
    logo: assets/logos/nbislogo-green.svg
    favicon: assets/logos/nbislogo-green.svg
    left:
      - href: index.qmd
        text: Home
      # - schedule.qmd
      - info.qmd
      - syllabus.qmd
  page-footer:
    border: false
    left: "2024 [NBIS](https://nbis.se) | [GPL-3 License](https://choosealicense.com/licenses/gpl-3.0/)"
    right: "Published with [Quarto](https://quarto.org/) v<?quarto.version?>"


from: markdown+emoji
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/apa.csl
# bibliography: assets/bibliography.bib

format:
  nbis-course-html:
    toc: true
    embed-resources: false
    date: last-modified
    date-format: "DD-MMM-YYYY"
    code-link: true
    code-block-border-left: "#a7c947"
    lightbox:
      match: auto

execute:
  echo: true
  warning: false
  cache: true
  include: true
  autodep: true
  eval: true
  error: true
  freeze: auto

knitr:
  opts_chunk:
    code-fold: false
    tidy: true
    comment-char: "#>"
    fig-format: svg
    engine.opts:
      dvisvgm.opts: --font-format=woff
      template: assets/www/tikzfig.tex

# jupyter:
#   kernelspec:
#     name: "pgip"
#     language: "python"
#     display_name: "Python 3"

    
extensions:
  - nbis-course
  - fontawesome
