project:
  type: website
  output-dir: _site
  preview:
    port: 8899
  render:
    - index.qmd
    - schedule.qmd
    - syllabus.qmd
    - info.qmd
    - precourse.qmd

website:
  title: "Population Genomics In Practice H25"
  navbar:
    logo: assets/logos/nbislogo-green.svg
    favicon: assets/logos/nbislogo-green.svg
    left:
      - href: index.qmd
        text: Home
      - schedule.qmd
      - contents.qmd
      - syllabus.qmd
      - info.qmd
      - precourse.qmd
  page-footer:
    border: false
    left: "2025 [NBIS](https://nbis.se) | [GPL-3 License](https://choosealicense.com/licenses/gpl-3.0/)"
    right: "Published with [Quarto](https://quarto.org/) v<?quarto.version?>"

from: markdown+emoji
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/apa.csl
bibliography: assets/bibliography.bib

format:
  nbis-course-html:
    theme: assets/css/custom.scss
    toc: true
    embed-resources: false
    date: last-modified
    date-format: "DD-MMM-YYYY"
    code-link: true
    code-block-border-left: "#a7c947"
    fontsize: 1.7em
    grid:
      body-width: 1200px
    lightbox:
      match: auto

execute:
  echo: true
  warning: false
  cache: true
  include: true
  autodep: true
  eval: true
  error: true
  freeze: auto

extensions:
  - nbis-course
  - fontawesome
